# This is a basic workflow that is manually triggered

name: Deploy backend to VPS

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    # Inputs the workflow accepts.
    branches:
      - main
    paths-ignore:
      - '**'
      - '!pdftools-frontend/**'
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.LIVE_SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_USER_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            sudo source ../env/bin/activate
            git commit -am "${{ github.event.head_commit.message }}"
            git pull ${{secrets.REPO_URL}}
            pip3 install -r requirements.txt
            sudo systemctl restart gunicorn
