# This is a basic workflow that is manually triggered

name: Deploy frontend

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    # Inputs the workflow accepts.
    branches:
      - main
    paths:
      - 'pdftools-frontend/**'
      

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Deploy the react frontend to server
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.LIVE_SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_USER_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git commit -am "${{ github.event.head_commit.message }}"
            git pull ${{secrets.REPO_URL}}
            cd pdftools-frontend/
            sudo ./deploy_frontend.sh
            sudo systemctl restart gunicorn
